SOURCES = {
    'web': 'https://github.com/h5bp/Front-end-Developer-Interview-Questions/blob/main/src/questions/javascript-questions.md',
    'frontend': 'https://github.com/yangshun/front-end-interview-handbook',
    'backend': 'https://github.com/Snailclimb/JavaGuide',
    'system': 'https://github.com/donnemartin/system-design-primer',
    'llm': 'https://github.com/llmgenai/LLMInterviewQuestions',
    'ai': 'https://github.com/shahshrey/AI_engineering_interview_questions',
    'ml': 'https://github.com/chiphuyen/ml-interviews-book',
}

ROWS = [
('closure','闭包 (Closure)','closure|closures|闭包|lexical closure|词法闭包|闭包捕获','web',
 '函数与其定义时的词法环境组成闭包，使函数在外层调用结束后仍可访问捕获的变量。',
 '捕获的是变量绑定而非必然的值副本；回调、工厂函数和私有状态常利用闭包。长寿命监听器若捕获大型对象会延长其存活时间，应在生命周期结束时解绑。',
 'var循环中定时器为什么常打印相同值？','var共享同一函数级绑定，回调执行时循环已结束；let为每次迭代创建绑定，也可用函数参数显式传值。',
 '闭包一定造成内存泄漏吗？','不会；只要闭包可达，其捕获环境就合理存活。泄漏是无用监听器等仍被引用，需解除根引用而不是禁止闭包。'),
('promise','Promise 异步结果','promise|promises|期约|promise chaining|promise.all|promise.allsettled','web',
 'Promise表示异步操作最终成功的值或失败原因，状态从pending一次性变为fulfilled或rejected。',
 'then回调进入微任务队列，返回值继续传递到链上的新Promise。执行器同步运行；Promise本身不等于线程，也不提供通用取消，需要底层任务配合AbortSignal。',
 'Promise.all有一个失败，其他任务会被取消吗？','不会，它只提前拒绝聚合结果；已启动操作继续。需要显式取消信号，或用allSettled收集所有结果。',
 'then返回Promise与普通值有什么区别？','返回普通值让下一段收到该值；返回Promise会采纳其最终状态，实现异步链；抛异常使返回的Promise拒绝。'),
('async-await','异步等待 (Async Await)','async await|async/await|await|async function|异步等待|异步函数','web',
 'async函数返回Promise，await暂停当前异步函数后续代码直到被等待值完成，不阻塞整个JavaScript线程。',
 'await之后的继续执行通过微任务调度。独立IO逐一await会意外串行，可先启动再聚合等待；错误沿Promise拒绝传播，可用try/catch处理。',
 '为什么数组forEach里await没有等待所有元素？','forEach不消费回调返回的Promise。串行用for...of，并行用map生成Promise数组后await Promise.all。',
 'async函数里CPU密集循环会阻塞页面吗？','会，async只改变结果协议；同步循环仍占主线程，应拆分工作或迁移到Web Worker。'),
('prototype-chain','原型链 (Prototype Chain)','prototype|prototype chain|prototypal inheritance|原型|原型链|原型继承','web',
 '对象查找属性时，先查自身，再沿内部原型引用逐级查找，直到找到属性或抵达null。',
 '构造函数prototype与实例的原型引用不同；class是基于原型机制的语法。修改共享原型会影响多个实例，动态变更原型还可能破坏引擎优化。',
 'hasOwnProperty与in有什么区别？','前者检查自身属性，in包含原型链属性；无原型对象可用Object.hasOwn来安全检查自身属性。',
 '原型污染如何发生？','不可信键被递归写入__proto__或constructor.prototype等共享原型入口；限制危险键、校验输入并使用合适的字典结构。'),
('event-delegation','事件委托 (Event Delegation)','event delegation|事件委托|事件代理|event bubbling|事件冒泡|event capturing','web',
 '事件委托在祖先节点设置监听器，通过事件传播和目标匹配处理多个后代元素的交互。',
 '捕获阶段向目标传播，冒泡阶段向祖先返回。target是原始目标，currentTarget是当前监听节点；Shadow DOM还涉及事件重定向和composedPath。',
 '动态列表为什么适合事件委托？','新增子节点无需逐个绑定，祖先监听仍可处理；需要校验closest匹配结果属于当前容器。',
 'preventDefault和stopPropagation分别影响什么？','前者取消可取消事件的默认行为，后者停止继续传播；两者互不等价，也不自动阻止同节点其他监听器。'),
('debounce-throttle','防抖与节流 (Debounce Throttle)','debounce|throttle|debouncing|throttling|防抖|节流','frontend',
 '防抖将连续触发合并为安静窗口后的调用；节流限制单位时间内执行频率，适用于不同交互需求。',
 '搜索输入常用防抖，滚动采样常用节流；要明确leading、trailing及最大等待时间。旧网络请求可能晚到，仍需要取消或序号校验。',
 '搜索框有防抖为什么仍会显示旧结果？','防抖只控制发起次数，不保证响应顺序；使用AbortController取消旧请求或用递增请求ID拒绝过期响应。',
 '拖动进度条应使用防抖还是节流？','持续反馈可节流或rAF合帧，松手时立即提交最终值；纯尾沿防抖会让拖动过程没有反馈。'),
('dom-tree','文档对象模型 (DOM)','dom|document object model|DOM树|文档对象模型|dom tree|document tree','frontend',
 'DOM把HTML文档表示为可由脚本读写的节点树，是页面结构、事件与渲染的操作接口。',
 'DOM树与布局树不完全相同，display:none节点不参与布局。批量写入后再读取布局尺寸可能触发同步布局，交错读写会形成layout thrashing。',
 'innerHTML和textContent的安全差异是什么？','innerHTML解析标记，外部文本可能注入可执行内容；textContent写纯文本。富文本需明确可信边界与消毒策略。',
 '为什么修改DOM后立刻读取offsetWidth可能变慢？','浏览器必须先完成挂起的样式和布局计算才能给出尺寸，多次交错读写导致反复同步布局。'),
('css-flexbox','弹性布局 (Flexbox)','flexbox|flex layout|flex|弹性布局|flex-shrink|flex-basis','frontend',
 'Flexbox是一维布局模型，沿主轴分配剩余空间，并控制交叉轴对齐和换行。',
 'flex-basis决定基础尺寸，grow/shrink分配剩余或不足空间。子项默认min-width:auto可能被长文本撑开，min-width:0允许收缩并配合溢出策略。',
 '为什么flex:1的面板仍被长文件名撑破？','自动最小尺寸可能保留min-content宽度；给该子项min-width:0，再选择换行、截断或内部滚动。',
 'flex-wrap能替代二维网格吗？','不完全能；每行独立分配空间，跨行列宽不一定对齐。需要跨行对齐与区域布局时使用CSS Grid。'),
('css-grid','网格布局 (CSS Grid)','css grid|grid layout|grid|网格布局|grid-template-columns|二维布局','frontend',
 'CSS Grid同时定义行和列，把页面区域或模块安排到二维网格中。',
 'fr分配可用空间，minmax约束轨道上下限，grid-column可跨多列。minmax(0,1fr)能避免内容最小尺寸把等分轨道撑破。',
 'auto-fill和auto-fit有何差别？','两者都创建尽可能多的轨道；auto-fit会折叠未占用轨道，让已有内容扩大，而auto-fill保留空轨道。',
 '架构图为什么适合Grid而不是绝对定位？','Grid保留内容驱动的尺寸与行列关系，文字变长仍可布局；连线可在布局完成后读取模块边界绘制。'),
('resize-observer','尺寸观察器 (ResizeObserver)','resizeobserver|resize observer|尺寸观察器|元素尺寸监听|resize callback|尺寸变化','frontend',
 'ResizeObserver观察元素内容盒或边框盒尺寸变化，能捕捉窗口之外的布局变化。',
 '分栏拖动、字体加载和父容器折叠都可能改变尺寸；回调中反复修改被观察尺寸会形成反馈循环，应合并重绘并在销毁时disconnect。',
 '监听window.resize为何不足以更新架构连线？','元素可在窗口不变时因分栏或内容变化改变尺寸，应观察实际画布或节点。',
 '如何避免ResizeObserver loop警告？','避免在回调中同步反复写回影响被观察尺寸的样式；分离读写、检查是否有实际变化，并按帧合并工作。'),
('intersection-observer','交叉观察器 (IntersectionObserver)','intersectionobserver|intersection observer|交叉观察器|可见性监听|懒加载观察|viewport intersection','frontend',
 'IntersectionObserver异步报告目标与根容器或视口交叉比例的变化，常用于懒加载和曝光统计。',
 'rootMargin可提前触发预取，threshold定义比例阈值。相交不一定意味着无遮挡可见，曝光统计还需停留时间与去重。',
 '图片懒加载为什么设置正rootMargin？','扩大判定范围，在图片进入视口前预加载，降低用户看到空白的概率，同时控制预取距离。',
 '相交回调触发一次就能算有效曝光吗？','不能，需结合可见比例、停留时长、页面可见状态与重复曝光口径。'),
('typescript-generics','泛型 (Generics)','generics|generic|泛型|type parameter|类型参数|generic constraint','frontend',
 '泛型用类型参数表达输入和输出之间的类型关系，使同一实现可安全处理多种类型。',
 '约束限制类型参数需要满足的能力，推断减少显式标注。泛型不是any，编译器仍检查关系；TypeScript类型在运行时擦除。',
 '泛型T和any有什么本质区别？','T保留调用点的类型联系，any跳过类型检查并传播不安全；identity<T>可保证输入输出同型。',
 '为什么接口泛型无法校验外部JSON？','类型会被擦除，网络数据仍需运行时schema或显式校验，不能仅靠类型断言。'),
('nodejs-runtime','Node.js 运行时','node.js|nodejs|node js|node runtime|Node运行时|libuv','frontend',
 'Node.js提供V8执行JavaScript以及事件循环、文件和网络IO接口，是浏览器之外的运行环境。',
 'libuv管理事件循环与部分工作线程池；网络IO多由操作系统异步机制处理。单个JS线程不代表整个进程只有一条线程。',
 'Node.js适合所有高并发场景吗？','适合IO密集任务；CPU密集计算会阻塞事件循环，需要worker_threads、进程或独立计算服务。',
 '大量同步文件调用为何拖慢HTTP接口？','它们阻塞事件循环，其他连接的回调无法处理；使用异步接口并限制并发以避免线程池和磁盘争用。'),
('react-library','React 界面库','React|reactjs|react.js|React UI|React组件|react library','frontend',
 'React以组件和状态描述界面，状态变化后计算新元素树并把必要更新提交到宿主环境。',
 'React UI库不同于Agent领域ReAct推理行动范式。渲染应保持纯净，副作用通过effect或事件处理；稳定key帮助协调过程识别列表项身份。',
 '列表为什么不宜总用数组下标作key？','插入删除或排序时下标变化会让组件状态错误复用；应使用稳定业务ID。',
 'setState后为什么不能立刻读取到新值？','更新进入调度并可能批处理，当前闭包仍持有本次渲染快照；依赖旧值更新使用函数式写法。'),
('browser-storage','浏览器存储 (Browser Storage)','localstorage|sessionstorage|indexeddb|browser storage|浏览器存储|本地存储API','frontend',
 '浏览器存储提供不同生命周期、容量与访问方式的客户端状态保存能力。',
 'localStorage同步且按origin隔离；sessionStorage按页面会话隔离；IndexedDB异步并支持事务。敏感数据需考虑XSS访问风险与存储权限失败。',
 '为什么不把大量事件流放localStorage？','序列化和同步写入阻塞主线程，容量也有限；大量结构化数据适合IndexedDB或后端持久化。',
 'sessionStorage是否能跨标签页实时共享？','通常每个顶层浏览上下文有独立会话存储，不能当共享总线；跨页通信可用BroadcastChannel。'),
('accessibility-a11y','无障碍访问 (Accessibility)','accessibility|a11y|无障碍|aria|键盘访问|screen reader','frontend',
 '无障碍设计让键盘、屏幕阅读器及不同感知能力的用户都能理解和操作界面。',
 '优先使用原生button、label、details等语义元素；自定义组件还需键盘行为、焦点管理、可访问名称和可见状态。ARIA只描述语义，不自动实现操作。',
 'div加role=button就等价于button吗？','不等价，仍需tabindex、Enter/Space响应、禁用行为与焦点样式；原生button通常更可靠。',
 '模态框关闭后焦点应该在哪里？','回到触发打开的控件；打开时聚焦合适内容并约束焦点，保证Escape及关闭按钮可用。'),
('serialization','序列化 (Serialization)','serialization|serialize|deserialize|deserialization|序列化|反序列化','backend',
 '序列化把内存数据转为可传输或持久化的字节/文本格式，反序列化执行逆向解释。',
 'JSON可读但缺少原生日期和二进制类型，Protobuf紧凑但需要schema演进约定。反序列化不可信对象可能执行危险行为，边界应限制类型和大小。',
 'JSON序列化为什么会丢失类方法？','JSON表达基础数据，不编码原型与可执行方法；接收端须显式构造领域对象而不是期待自动恢复行为。',
 '接口字段改名如何保证兼容？','采用版本或兼容读路径，先允许旧新字段再迁移消费者；避免改变已有字段含义或必填约束而无协调。'),
('middleware','中间件 (Middleware)','middleware|中间件|request middleware|拦截器|interceptor|middleware chain','system',
 '中间件在请求或事件处理链中封装横切功能，如认证、日志、追踪、限流与异常转换。',
 '执行顺序决定上下文是否可用和响应能否被修改；洋葱式中间件在调用下一层前后分别执行。读取请求体、重复响应和吞掉异常是常见陷阱。',
 '认证与访问日志中间件谁在外层？','通常日志在外层以记录认证失败，追踪初始化更靠外；具体顺序取决于是否需要用户身份和统一错误结果。',
 '为什么中间件读完请求体后业务拿不到数据？','流通常只能消费一次；应缓存有界内容或使用框架统一解析器，把解析结果放上下文。'),
('dependency-injection','依赖注入 (Dependency Injection)','dependency injection|DI|IoC|控制反转|依赖注入|inversion of control','backend',
 '依赖注入让对象需要的协作者由外部提供，而不是在对象内部固定创建，属于控制反转的实现方式。',
 '构造器注入使依赖显式且利于替换测试；容器可管理生命周期与作用域。循环依赖通常提示职责边界问题，不能仅靠延迟代理掩盖。',
 '依赖注入为什么有利于测试？','测试可传入内存实现或受控替身，避免真实网络和数据库，同时保持业务依赖接口不变。',
 '单例注入请求作用域对象会有什么问题？','生命周期不匹配可能捕获已失效状态或跨请求共享信息；用作用域代理或按请求显式传入。'),
('authentication','身份认证 (Authentication)','authentication|authenticate|身份认证|authn|登录认证|identity verification','backend',
 '身份认证确认调用者是谁，通常通过密码、会话、签名令牌或多因素凭据验证。',
 '认证不同于授权；密码保存应使用带盐慢哈希，登录接口需防暴力尝试。会话轮换与注销策略决定凭据失窃后的风险窗口。',
 '认证成功为什么仍可能返回403？','身份已知但没有资源权限；401通常表示需要认证或凭据无效，403表示访问被拒绝。',
 '刷新令牌与访问令牌为什么分开？','访问令牌短寿命降低泄漏窗口，刷新令牌用于获取新访问令牌并可轮换撤销，需更严格存储。'),
('authorization','访问授权 (Authorization)','authorization|authorize|授权|authz|rbac|abac','backend',
 '授权判断某个身份是否允许对特定资源执行动作，可基于角色、属性和资源归属。',
 'RBAC按角色分配权限，ABAC结合主体、资源和环境属性。前端隐藏按钮不构成授权，服务端需逐请求检查，特别是对象级访问。',
 '如何防止用户修改URL读取别人的订单？','后端查询必须结合当前身份与资源归属做对象级权限校验，不能只检查是否登录。',
 'RBAC角色爆炸时如何优化？','区分稳定岗位角色与资源/租户属性，将细粒度条件交给策略或ABAC，保持权限审计清晰。'),
('oauth2','OAuth 2.0 委托授权','oauth|oauth2|oauth 2.0|委托授权|authorization code|pkce','backend',
 'OAuth 2.0让应用获得资源访问授权，而无需直接取得用户在资源服务上的密码。',
 '授权码流程通过后端或PKCE交换令牌，state绑定请求防CSRF。OAuth不是完整登录身份协议，登录常在其上使用OpenID Connect。',
 '公开客户端为什么需要PKCE？','它无法安全保存client secret；用随机verifier和challenge绑定授权请求与兑换，降低授权码被截获后的风险。',
 'OAuth access token能直接当用户身份凭证吗？','不能普遍这样做；访问令牌是资源授权凭证，登录应验证OIDC ID token或可信用户信息接口。'),
('jwt-token','JSON Web Token (JWT)','jwt|json web token|签名令牌|bearer token|access token|令牌校验','backend',
 'JWT是承载声明的紧凑令牌格式，常用数字签名保障完整性，但载荷通常可直接解码。',
 '校验需固定允许算法，验证签名、发行者、受众和有效期。无状态验证方便扩展，但撤销和权限更新需短有效期或外部状态配合。',
 'JWT签名是否意味着内容已加密？','不是，常见JWS只签名，header和payload可被解码；敏感内容应避免放入或采用合适加密方案。',
 'JWT如何支持立即退出登录？','可维护撤销列表或令牌版本并查询状态，也可短访问令牌配合撤销刷新令牌；纯离线验证无法即时获知撤销。'),
('deadlock','死锁 (Deadlock)','deadlock|死锁|circular wait|循环等待|lock ordering|锁顺序','backend',
 '多个执行单元彼此等待对方持有的资源，使所有参与者都无法继续推进。',
 '互斥、持有并等待、不可抢占与循环等待共同构成经典必要条件。统一锁顺序可破坏环，超时只能限制等待时长，还需正确回滚。',
 '数据库死锁后仅重试最后一条SQL安全吗？','通常应回滚并重试整个事务，确保业务不处于部分执行状态，同时保证重试的幂等性。',
 '如何区分死锁和普通锁竞争？','观察等待图是否形成环、线程栈是否长期固定；竞争仍会推进，死锁需要释放资源或中止参与者。'),
('race-condition','竞态条件 (Race Condition)','race condition|data race|竞态|数据竞争|check then act|竞争条件','backend',
 '程序结果依赖不可控的执行时序时会出现竞态；数据竞争是缺少同步的并发冲突访问这一特定情况。',
 '先检查再写入不是原子操作，即使每次读写本身线程安全仍可能出错。锁、原子操作、数据库唯一约束或事务需覆盖完整不变量。',
 '线程安全Map能保证不存在时才创建只执行一次吗？','单独contains和put不保证；需要原子compute/putIfAbsent或外层同步，并考虑创建副作用是否重复。',
 '加volatile能解决计数器++丢更新吗？','不能，它不把读改写合成原子操作；应使用原子计数器或锁。'),
('mutex-semaphore','互斥锁与信号量 (Mutex Semaphore)','mutex|semaphore|互斥锁|信号量|互斥量|counting semaphore','backend',
 '互斥锁保护一次只能一个持有者进入的临界区；计数信号量限制可同时使用资源的数量。',
 '锁通常有所有权和释放规则，信号量表达许可数量。必须在异常路径释放资源，避免持锁执行不受控网络操作扩大阻塞。',
 '限制同时最多10个模型请求应使用什么？','计数信号量或有界并发队列，finally释放许可；限并发不同于每秒请求速率限制。',
 '互斥锁为什么不能只锁写操作？','若读操作要求与写一致，也需同步或快照机制，否则会读取中间状态；具体取决于不变量。'),
('coroutine','协程 (Coroutine)','coroutine|coroutines|协程|asyncio|cooperative scheduling|协作式调度','backend',
 '协程是可挂起和恢复的执行单元，常由用户态调度器在少量线程上协作执行大量IO任务。',
 '协程在await等挂起点让出执行，不自动获得CPU并行。阻塞系统调用或长计算会阻塞事件循环，取消也需在可取消点及时响应。',
 'Python asyncio里调用time.sleep有什么影响？','它阻塞当前线程及其事件循环；应使用await asyncio.sleep，阻塞库调用可转到受控线程执行。',
 '协程多就一定比线程快吗？','不是，收益主要是降低大量IO等待的调度开销；CPU计算、上下文切换和库兼容性决定实际效果。'),
('connection-pool','连接池 (Connection Pool)','connection pool|连接池|pooling|连接复用|pool exhaustion|连接耗尽','system',
 '连接池复用建立成本较高的数据库或网络连接，并限制同时占用下游资源的数量。',
 '池大小、获取超时、空闲回收和连接健康检查需协调；泄漏连接会耗尽池，盲目放大池会把压力转移给数据库。',
 '接口慢时为何不能直接把连接池调到几千？','数据库处理能力有限，更大池可能增加排队、锁竞争与内存消耗；先测服务时间、并发和下游容量。',
 '如何定位连接池耗尽？','观察活跃/空闲/等待数、持有时间与事务栈，检查异常路径是否归还及慢查询是否长时间占用。'),
('backpressure','背压 (Backpressure)','backpressure|back pressure|背压|反压|bounded queue|有界队列','system',
 '背压让下游处理能力反向限制上游生产速度，避免缓冲无限增长导致延迟和内存失控。',
 '有界队列、消费许可、暂停读取与丢弃策略都是实现手段。对必须可靠的数据采用持久化或拒绝重试，对可合并状态可保留最新值。',
 'SSE客户端很慢时服务器应该怎么办？','给每客户端有界缓冲，按数据语义合并、断开或要求重连补拉；不能让一个慢客户端阻塞所有广播。',
 '限流和背压有什么区别？','限流按预设预算限制流量；背压由实际消费能力反馈调整生产，两者可以共同保护系统。'),
('load-balancer','负载均衡 (Load Balancer)','load balancer|load balancing|负载均衡|round robin|least connections|健康检查','system',
 '负载均衡在多个后端实例之间分配请求，提高吞吐和可用性。',
 '轮询简单，最少连接适合耗时差异，哈希可保持亲和性。健康检查应反映可服务能力，故障摘除和连接排空避免继续发送到失效实例。',
 '最少连接是否等于最少负载？','不一定，连接可能空闲或请求成本差异巨大，HTTP/2多路复用也改变含义；可结合活跃请求与延迟。',
 '会话粘滞有什么代价？','可能造成热点且削弱故障迁移；共享会话存储或无状态设计能减少对粘滞的依赖。'),
('write-ahead-log','预写日志 (WAL)','wal|write ahead log|write-ahead logging|预写日志|redo log|重做日志','backend',
 'WAL要求数据页持久化前先把对应修改日志持久化，使崩溃后可重放已提交修改。',
 '顺序追加日志通常比随机写数据页高效。提交是否真正落盘取决于fsync与刷盘策略，检查点缩短恢复时需保证日志和数据一致。',
 '写了WAL就绝对不丢已提交事务吗？','取决于确认前是否把日志持久化以及存储设备保证；异步刷盘可能牺牲最近事务耐久性。',
 '检查点为什么不能随便删除旧日志？','必须确认对应数据页和复制消费者都不再依赖日志，否则恢复或追赶会缺失必要记录。'),
('lsm-tree','日志结构合并树 (LSM Tree)','lsm|lsm tree|lsm-tree|日志结构合并树|sstable|compaction','backend',
 'LSM以内存有序表和不可变磁盘有序文件组织数据，通过批量写入和合并提升写吞吐。',
 '写入通常先WAL再MemTable，刷盘形成SSTable，后台compaction整理版本和墓碑。写放大、读放大、空间放大互相制约。',
 'LSM删除后磁盘为何没有立即变小？','先写墓碑遮蔽旧值，等合并确认旧版本不再需要才回收；快照和复制可能延迟清理。',
 'Bloom Filter能替代SSTable索引吗？','不能，它只帮助判定肯定不存在或可能存在；命中仍需索引和数据查找，且有误判。'),
('transaction-isolation','事务隔离 (Transaction Isolation)','transaction isolation|隔离级别|read committed|repeatable read|serializable|事务隔离','backend',
 '事务隔离规定并发事务能观察到哪些中间或已提交状态，在吞吐与一致性之间取舍。',
 '隔离通常由锁和MVCC组合实现；不同数据库对同名级别的具体语义可能不同。快照隔离仍可能发生写偏斜，需串行化或显式约束。',
 '可重复读一定等于串行化吗？','不等于，重复读取稳定不代表所有并发执行等价串行；写偏斜等跨行约束仍可能被破坏。',
 '如何保障两个医生不能同时下班？','必须把至少一人在岗的不变量纳入可串行化事务、锁定共同资源或数据库约束，而非只读各自快照。'),
('database-migration','数据库迁移 (Database Migration)','migration|migrations|schema migration|数据库迁移|模式迁移|expand contract','backend',
 '数据库迁移把表结构和数据演进记录成可执行、有版本的变更，使部署环境保持一致。',
 '大表修改需关注锁和回填成本；滚动部署采用先扩展兼容结构、迁移读写、最后收缩旧字段的流程。回滚代码不等于能无损回滚数据。',
 '线上字段改名为什么不直接rename？','旧实例仍可能使用旧名；先新增兼容字段并双写/回填，切换读取后再移除，避免部署窗口故障。',
 '迁移脚本可以重复执行吗？','需由版本记录确保一次应用，或设计幂等步骤；数据回填还需断点和批量控制。'),
('inverted-index','倒排索引 (Inverted Index)','inverted index|倒排索引|posting list|倒排表|词项索引|term dictionary','system',
 '倒排索引从词项映射到包含它的文档及位置，支持快速全文检索。',
 '分词、归一化和停用词决定检索粒度，posting list可做交并及跳跃合并。更新常写新段后合并，短语搜索还需要位置信息。',
 '倒排索引为何比逐文档扫描快？','只访问查询词对应候选列表，避免读取无关文档；常见词仍可能很大，需要压缩和跳表优化。',
 '为什么中文分词词典变了可能需要重建索引？','索引与查询分析器产生的词项必须兼容，否则同一文本对应不同token会漏召回。'),
('bm25-ranking','BM25 检索打分','bm25|okapi bm25|词频饱和|文档长度归一化|bm25 ranking|稀疏检索评分','ai',
 'BM25根据查询词的文档稀有度、词频饱和与文档长度对候选文档进行相关性打分。',
 'k1控制词频收益饱和，b调节长度归一化。它是词面匹配而非向量语义模型，精确术语有效，但同义改写需要扩展词或混合检索。',
 '同一个关键词重复100次为何不应得分线性增长？','重复堆词不代表相关性等比例增加，词频饱和抑制这种操纵，同时保留出现多次的有限收益。',
 'BM25和向量检索怎样结合？','分别召回后用RRF等排名融合，再用重排模型精排；不要直接相加不可比的原始分数。'),
('rag-pipeline','检索增强生成 (RAG)','rag|retrieval augmented generation|retrieval-augmented generation|检索增强生成|RAG pipeline|rag系统','llm',
 'RAG在生成前检索外部资料并提供给模型，使回答利用可更新、可追溯的知识。',
 '离线处理负责清洗、分块和索引，在线链路负责查询改写、召回、重排与带引用生成。召回正确不等于生成忠实，需分层评测。',
 'RAG与微调分别适合解决什么问题？','RAG适合更新知识、证据引用和权限过滤；微调适合行为、风格或特定任务能力，两者可组合。',
 'RAG回答错了怎么定位？','先看目标文档是否入库，再看召回排名、上下文截断和生成是否忠实，按环节指标排查而非只换模型。'),
('document-chunking','文档分块 (Chunking)','chunking|chunk|chunks|文档分块|semantic chunking|chunk overlap','llm',
 '分块把长文档拆成适合索引和模型上下文的片段，同时尽可能保留完整语义与来源位置。',
 '固定长度便宜但可能切断段落；结构或语义分块更完整但复杂。块过小缺上下文，过大稀释召回，重叠会增加索引成本与重复证据。',
 'chunk越小召回越精准吗？','不必然，缺少主体和前提会让向量失真；需以查询集评测召回与回答质量，并保留父文档上下文。',
 '表格跨页时如何分块？','保留表头、单位和行列关联，必要时按行组分块并附共同表头及页码，避免把数字与语义拆开。'),
('reranker-model','检索重排器 (Reranker)','reranker|reranking|cross encoder|cross-encoder|检索重排|重排序模型','ai',
 '重排器对粗召回候选进行更昂贵的查询—文档相关性判断，把真正相关的证据排到前面。',
 '双塔适合离线向量化高效召回，交叉编码器联合编码查询与文档捕捉细粒度交互；只对Top-K执行以控制延迟。',
 '有重排器是否就不需要提高召回率？','仍需要，重排只能调整候选顺序，无法恢复根本没有召回的正确文档。',
 '如何选择重排候选数量？','用验证集测候选召回率与端到端延迟，寻找收益递减拐点；长文档还要控制token预算。'),
('rrf-fusion','倒数排名融合 (RRF)','rrf|reciprocal rank fusion|排名融合|倒数排名融合|hybrid search|混合检索','ai',
 'RRF把多个检索器的排名按1/(常数+名次)累加，融合不同量纲的检索结果。',
 '它依赖名次而非原始分数，适合融合BM25和向量检索。应按文档ID去重，常数控制头部优势，融合后仍可重排。',
 '为何不直接相加BM25和余弦相似度？','两者尺度和分布不同，会让一方支配；可校准分数，也可用只依赖排名的RRF。',
 '某路召回很多重复片段怎样处理？','先按稳定文档或片段ID去重，必要时按父文档做多样性约束，避免融合结果被单一来源占满。'),
('tokenizer','分词器 (Tokenizer)','tokenizer|tokenization|bpe|sentencepiece|分词器|byte pair encoding','llm',
 'Tokenizer把文本映射为模型词表中的token ID，并负责将生成ID还原为文本。',
 'BPE逐步合并高频字节或符号对，词表大小影响序列长度与参数规模。一个英文单词或汉字可能对应多个token，不能简单按词数估预算。',
 '为什么换模型后相同文本token数不同？','词表、合并规则、特殊token及聊天模板不同；预算应使用对应tokenizer或保守估算。',
 '新增特殊token后为什么还需训练？','新ID对应的embedding和输出权重没有学到语义，需要正确初始化并用任务数据学习。'),
('attention-mechanism','注意力机制 (Attention)','attention|self attention|self-attention|注意力|qkv|scaled dot product attention','llm',
 '注意力用查询与键的相似度给值向量加权聚合，让表示根据上下文选择相关信息。',
 '缩放点积注意力计算softmax(QK转置/根号d)V；缩放避免高维点积过大导致softmax饱和。因果掩码阻止看到未来token。',
 '为什么QK点积要除以根号d？','在分量方差近似稳定时点积方差随d增长，缩放保持数值范围，缓解softmax饱和与梯度过小。',
 'self-attention和cross-attention差在哪？','前者Q/K/V来自同一序列表示，后者Q来自目标而K/V来自另一序列，用于对齐外部信息。'),
('flash-attention','FlashAttention 高效注意力','flashattention|flash attention|flash-attention|IO-aware attention|分块注意力|在线softmax','ai',
 'FlashAttention通过分块与融合计算减少显存读写，精确计算注意力而不显式保存完整注意力矩阵。',
 '它利用在线softmax维护归一化统计，将更多中间计算保留在片上内存。速度收益取决于硬件和序列形状，主要优化IO与显存而非改变注意力语义。',
 'FlashAttention属于稀疏或近似注意力吗？','标准FlashAttention不是，它保持精确注意力数学结果，仅重排计算与内存访问，数值误差来自浮点。',
 '它能把注意力计算复杂度从平方降成线性吗？','标准全注意力仍需平方规模计算，但显著减少中间显存占用与访存开销。'),
('gradient-descent','梯度下降 (Gradient Descent)','gradient|gradient descent|梯度|梯度下降|sgd|随机梯度下降','ml',
 '梯度下降沿损失函数负梯度方向更新参数，以迭代降低训练目标。',
 '全批梯度代价高，小批随机梯度有噪声但易扩展。学习率、批量大小和梯度尺度决定稳定性；梯度为零不一定是全局最优。',
 '学习率过大会出现什么现象？','损失震荡或发散，更新跨过稳定区域；应检查数值尺度、数据异常及调度，而非只增加训练轮数。',
 '为什么大batch不总是更好？','降低梯度噪声但占显存，更新次数与泛化特性改变；吞吐收益和统计效率需要共同评估。'),
('backpropagation','反向传播 (Backpropagation)','backpropagation|backprop|反向传播|autograd|自动微分|chain rule','ml',
 '反向传播应用链式法则，从损失沿计算图反向计算各参数梯度。',
 '前向保存所需中间值，反向局部梯度累乘累加。动态图框架自动记录操作；detach切断梯度，原地修改可能破坏反向需要的值。',
 '反向传播与梯度下降是同一件事吗？','不是，反向传播计算梯度，优化器使用梯度更新参数；可以有梯度却选择不更新。',
 '为什么每步训练要清理累计梯度？','很多框架默认累加到grad，若不清理会意外混合多步梯度；有意梯度累积时则在指定边界清零。'),
('adamw-optimizer','AdamW 优化器','adamw|adam|optimizer|优化器|weight decay|权重衰减','ml',
 'Adam维护梯度一阶和二阶矩估计进行自适应更新，AdamW将权重衰减与梯度更新解耦。',
 '矩估计需偏差校正；epsilon保障数值稳定。权重衰减、学习率和调度相互影响，偏置及归一化参数常采用不同衰减策略。',
 'Adam中的L2正则为什么不等于AdamW？','自适应缩放会同时作用于加到梯度中的L2项，解耦衰减则直接缩放参数，产生不同更新。',
 'Adam训练大模型显存为何比权重本身多？','还需梯度、一二阶矩以及可能的高精度主权重，激活和临时缓冲进一步增加占用。'),
('gradient-accumulation','梯度累积 (Gradient Accumulation)','gradient accumulation|梯度累积|micro batch|microbatch|effective batch size|有效批量','ml',
 '梯度累积把多个小批次的梯度相加后统一更新，模拟更大的有效batch而降低单次激活显存。',
 '损失需按累积步数缩放，优化器和学习率调度在更新步执行。BatchNorm、随机性和通信策略可能使其不完全等价于单个大batch。',
 '累积四步时每个microbatch损失如何处理？','若每批损失是均值，通常除以四后反向，四步后更新并清零；不等长batch需按样本或token数加权。',
 '梯度累积一定提升训练速度吗？','主要节约激活显存，增加前后向次数可能更慢；分布式可延迟梯度同步降低通信。'),
('activation-checkpointing','激活检查点 (Activation Checkpointing)','activation checkpointing|gradient checkpointing|激活检查点|梯度检查点|activation recomputation|重计算','ai',
 '激活检查点只保存部分前向中间结果，反向时重新计算缺失部分，用计算换显存。',
 '检查点粒度影响重复计算与内存峰值；随机层需正确恢复随机状态。它不同于保存模型训练状态的持久化checkpoint。',
 '为什么开启检查点后吞吐可能下降？','反向前需要额外前向重计算，减少显存但增加计算时间；收益在能用更长序列或更大batch时体现。',
 '带dropout的重计算需要注意什么？','应复现同一随机掩码或遵循框架支持的随机状态机制，否则重计算图与原前向不一致。'),
('training-checkpoint','训练检查点 (Training Checkpoint)','checkpoint|checkpoints|训练检查点|断点续训|resume training|optimizer state','ml',
 '训练检查点保存恢复训练所需的模型权重及优化器、调度器、步数和随机状态。',
 '只保存权重适合推理或新任务初始化，精确续训还需优化器矩、数据采样位置和随机数。写入应原子发布并验证完整性。',
 '只加载模型权重继续训练为何轨迹不同？','优化器动量、学习率调度、数据顺序和随机状态未恢复，后续更新与原轨迹不同。',
 '分布式分片检查点如何避免半成品被加载？','各分片完成后再发布统一完成标记或manifest，加载前校验分片集合与版本，避免覆盖最后可用版本。'),
('sft-training','监督微调 (SFT)','sft|supervised fine tuning|supervised fine-tuning|监督微调|instruction tuning|指令微调','llm',
 'SFT在任务或指令示例上最小化目标回复的预测损失，使预训练模型学习期望行为和格式。',
 '数据质量、聊天模板与损失掩码通常比盲目加量重要。应区分用户提示和助手目标token，避免评测污染，并用独立集检查能力退化。',
 '训练聊天数据时为什么常屏蔽用户token损失？','目标是学习助手回复而非复述用户输入，屏蔽可将优化集中在目标输出；具体取决于训练目标。',
 'SFT能可靠替代实时知识库吗？','不能保证知识可更新或可追溯；事实频繁变化时使用检索，SFT更适合行为和任务模式。'),
('lora-adapter','低秩适配 (LoRA)','lora|low rank adaptation|low-rank adaptation|低秩适配|adapter|适配器微调','llm',
 'LoRA冻结基础权重，用低秩矩阵乘积表示增量更新，减少训练参数与优化器状态开销。',
 '秩r控制表达容量，缩放系数和插入层决定学习强度。推理可合并增量，也可保留多适配器；基础模型版本必须一致。',
 'LoRA为什么省显存但不一定显著省前向计算？','基础模型仍需执行前向与部分反向传播，主要减少可训练参数、梯度和优化器状态。',
 'LoRA的rank越大越好吗？','更大秩增加容量和成本，可能过拟合；应依据数据规模、任务难度与验证集调参。'),
('dpo-training','直接偏好优化 (DPO)','dpo|direct preference optimization|直接偏好优化|preference pair|偏好对|chosen rejected','llm',
 'DPO使用同一提示下的偏好/非偏好回复对，直接优化策略相对参考模型的对数概率差。',
 '它不需要显式在线训练奖励模型再跑PPO，但仍依赖偏好数据质量与参考策略；beta控制偏离约束强度，离线分布偏差会影响效果。',
 'DPO为什么仍需要参考模型？','目标使用策略相对参考分布的概率比，约束偏离并连接到KL正则化偏好优化推导。',
 'DPO数据中chosen更长会有什么风险？','模型可能把长度学成偏好捷径；需检查长度分布、真实质量和分层评测，避免奖励错误特征。'),
('ppo-policy','近端策略优化 (PPO)','ppo|proximal policy optimization|近端策略优化|policy ratio|clip objective|策略裁剪','ml',
 'PPO通过限制新旧策略概率比对目标的贡献，减少单次更新过大导致训练不稳定。',
 '常用裁剪代理目标结合优势估计和值函数训练；裁剪不等于严格限制真实KL。LLM场景还要处理奖励尺度、序列长度和参考模型约束。',
 'PPO裁剪是否保证KL永远小于阈值？','不保证，裁剪限制代理目标某些区域的收益而非硬约束；仍需监控KL并采用提前停止或惩罚。',
 '为什么优势估计通常要做归一化？','改善优化尺度与稳定性，但需匹配批次/分组语义，不能随意把不同奖励口径混在一起。'),
('grpo-policy','组相对策略优化 (GRPO)','grpo|group relative policy optimization|组相对策略优化|group advantage|组内优势|组相对奖励','ai',
 'GRPO对同一提示采样一组候选，根据组内相对奖励构造优势，从而减少对独立价值网络的依赖。',
 '组内奖励差异提供学习信号；奖励全相同会使该组缺少相对区分。实现间在归一化、KL项与长度处理上有区别，应明确公式和版本。',
 '一组回答全部得0分会发生什么？','相对优势通常接近零，无法学习区分；需提高探索、多样性或使用提供分辨率的奖励，同时防止奖励投机。',
 '去掉价值网络是否意味着训练免费？','不是，仍要多候选生成、奖励计算和策略更新，采样开销可能成为主要瓶颈。'),
('precision-recall','精确率与召回率 (Precision Recall)','precision|recall|精确率|召回率|查准率|查全率','ml',
 '精确率是预测为正的样本中真正为正的比例，召回率是真正正样本中被找回的比例。',
 '阈值改变两者取舍；类别不平衡时准确率可能误导。检索Recall@K衡量前K结果找回目标的程度，需要明确相关集合与统计口径。',
 '核心文件筛选更应该优先哪个指标？','首先保证召回，避免重要入口漏选，再用精确率控制上下文噪声；同时报告预算导致的覆盖缺口。',
 '模型全部预测负类为何准确率仍很高？','当负类占绝大多数时准确率被多数类主导，应看正类召回、PR曲线和业务代价。'),
('ndcg-metric','排序质量 (NDCG)','ndcg|normalized discounted cumulative gain|归一化折损累计增益|dcg|排序指标|ndcg@k','ml',
 'NDCG用相关性等级和位置折损评价排序，再除以理想排序得分以便不同查询间比较。',
 '高相关结果越靠前贡献越高，适合多级相关性标签。增益函数与K值改变偏好，未标注文档不能简单视作真实不相关。',
 'NDCG为何比准确率更适合搜索排序？','排序不仅关心命中还关心位置和相关等级，NDCG显式考虑头部位置价值。',
 '离线NDCG上升线上点击未涨怎么办？','检查评测标签偏差、查询分布变化、展示位置和延迟；用在线实验验证而非假定指标完全一致。'),
('auc-roc','ROC 与 AUC','auc|roc|roc auc|受试者工作特征|曲线下面积|auc metric','ml',
 'ROC描述不同阈值下真正率和假正率，AUC可解释为随机正样本得分高于随机负样本的概率。',
 'AUC看全局排序，可能掩盖极不平衡场景的低精确率，也不表示概率校准。业务只用头部阈值时应同时看对应区域指标。',
 'AUC很高为什么报警仍多数是误报？','正类很稀少时少量假正率也对应大量负样本；应看PR指标、阈值及基准发生率。',
 'AUC高能说明输出0.8就是80%概率吗？','不能，AUC只评价排序；需用校准曲线、Brier分数等检查概率是否可靠。'),
('data-leakage','数据泄漏 (Data Leakage)','data leakage|label leakage|数据泄漏|标签泄漏|train test contamination|训练测试污染','ml',
 '数据泄漏指训练或特征使用了预测时不可获得的信息，导致离线效果虚高。',
 '常见于先全量预处理再切分、时间穿越特征、同用户样本跨集合及重复数据污染。切分方式应模拟真实部署时间和实体隔离。',
 '标准化为什么要只在训练集拟合？','全量均值方差包含验证集分布信息，会污染评测；训练统计应固定后用于验证和测试。',
 '推荐模型随机切分为什么可能高估效果？','未来行为或相近重复交互流入训练，不能模拟面向未来推荐；通常需时间切分并检查用户/物品口径。'),
('feature-store','特征平台 (Feature Store)','feature store|特征平台|特征库|online offline consistency|point in time join|特征一致性','ml',
 '特征平台管理特征定义、离线训练取数和在线推理服务，减少重复计算与训练服务偏差。',
 '时点正确连接确保训练样本只使用当时可见特征；在线/离线实现需保持语义一致，版本、延迟与新鲜度需可追踪。',
 '训练和线上都叫过去7天点击数为何仍不一致？','时间窗口边界、时区、延迟事件、去重和更新周期可能不同，需统一定义并做样本回放比对。',
 'point-in-time join解决什么问题？','按样本发生时间选择当时可用的特征版本，防止未来信息泄漏进入训练。'),
('negative-sampling','负采样 (Negative Sampling)','negative sampling|hard negative|负采样|困难负例|in batch negatives|in-batch negatives','ml',
 '负采样从大量未选中候选中选取训练负例，降低成本并提供区分信号。',
 '随机负例易但可能过于简单，困难负例有价值却可能含假负例；批内负例高效但受批次分布影响，采样偏差需校正。',
 '未点击样本一定是不喜欢吗？','不是，可能未曝光或未注意，负例需结合曝光和位置；否则把未知偏好误标成负类。',
 '困难负例越难越好吗？','过难样本可能是漏标正例或噪声，导致梯度冲突；应控制比例并检查标注与训练阶段。'),
('cross-entropy','交叉熵 (Cross Entropy)','cross entropy|cross-entropy|交叉熵|log loss|对数损失|negative log likelihood','ml',
 '交叉熵衡量目标分布与预测分布的差异，分类时常表现为真实标签负对数概率。',
 'softmax把logit映射到概率，数值实现需使用稳定的log-sum-exp。类别权重、标签平滑和mask改变训练目标，应与评价口径一致。',
 '为什么对softmax后概率再调用带logits的损失是错的？','该函数已内部执行稳定归一化，重复softmax改变概率和梯度，应按接口约定传原始logits。',
 '标签平滑能解决所有标签噪声吗？','不能，它降低过度自信但可能损害校准或少数类区分；仍需数据治理和独立评测。'),
('kl-divergence','KL 散度','kl|kl divergence|kullback leibler|KL散度|相对熵|relative entropy','ml',
 'KL散度衡量用一个概率分布近似另一个分布时的信息损失，通常不对称。',
 'KL非负但不是满足对称和三角不等式的距离。支持集不匹配可能导致无穷大；在策略对齐中常用于限制偏离参考策略。',
 'KL(P||Q)与KL(Q||P)优化行为一样吗？','不同，两者强调的概率区域不同，可能产生覆盖模式或集中模式的差异，不能随意交换。',
 'LLM对齐中为何监控相对参考模型的KL？','偏离过大可能损害原能力并放大奖励投机；KL是约束信号之一，但不能单独证明质量或安全。'),
('embedding-similarity','余弦相似度 (Cosine Similarity)','cosine similarity|余弦相似度|dot product|inner product|向量归一化|l2 normalization','ai',
 '余弦相似度衡量向量夹角；点积同时受方向和长度影响，归一化后两者排序一致。',
 '检索距离应匹配embedding训练目标，归一化改变长度信息。零向量需要边界处理，高维空间的分布与各向异性会影响阈值。',
 '为何不能给所有embedding模型用同一个相似度阈值？','模型尺度、训练目标和数据分布不同，分数不可直接比较，应基于验证集校准。',
 '归一化后欧氏距离与余弦相似度什么关系？','单位向量的平方欧氏距离等于2减2倍余弦值，因此最近邻排序等价。'),
('cpp-language','C++ 语言与资源管理','c++|cpp|cxx|C++语言|raii|resource acquisition is initialization','backend',
 'C++支持值语义、泛型和显式资源管理，RAII把资源生命周期绑定到对象构造与析构。',
 '智能指针表达所有权：unique_ptr独占，shared_ptr引用计数共享，weak_ptr观察而不延长寿命。异常展开会析构已构造的自动对象。',
 'shared_ptr循环引用为何泄漏？','环内引用计数彼此维持非零，需用weak_ptr打破所有权环或重新设计所有权关系。',
 'RAII为何比每条返回路径手动close可靠？','资源随作用域自动释放，覆盖正常返回和异常路径，减少遗漏；析构函数应避免抛出传播异常。'),
('python-language','Python 运行机制','python|python3|cpython|Python语言|python runtime|python interpreter','backend',
 'Python是动态类型语言，常见CPython实现把源代码编译成字节码并由解释器执行。',
 '引用计数配合循环垃圾回收管理对象；可变对象别名、默认参数求值时机和迭代器语义影响程序行为。线程并行能力取决于具体解释器与构建模式。',
 '函数默认参数为何不宜用空列表？','默认表达式在函数定义时求值一次，多次调用共享同一列表；用None并在调用中创建新列表。',
 '生成器相比列表的主要取舍是什么？','按需产生元素降低峰值内存，但通常一次消费且延迟执行；需要重复访问或随机索引时列表更合适。'),
('threading-http-server','多线程HTTP服务 (ThreadingHTTPServer)','ThreadingHTTPServer|threading http server|多线程HTTP服务|http.server|BaseHTTPRequestHandler|ThreadingMixIn','backend',
 'Python标准库的HTTPServer结合ThreadingMixIn，将接受的连接交给独立线程处理；请求方法由BaseHTTPRequestHandler的子类实现。',
 '长连接与慢客户端会持续占用线程，SSE需要考虑连接数、断开与写入超时。共享缓存和事件存储仍需同步；标准库服务适合本地工具，不具备完整生产网关的防护能力。',
 '为何单线程HTTP服务遇到SSE后其他接口可能卡住？','SSE处理函数长时间不返回，串行服务无法接收处理后续连接；并发处理可以隔离等待，但仍须限制资源占用和正确结束断开的流。',
 '换成ThreadingHTTPServer后共享字典就线程安全吗？','复合操作仍可能交错，例如先查缓存再构建会重复执行；应围绕共享状态更新加锁，避免把网络或模型调用放进全局锁。'),
('abort-controller','请求取消 (AbortController)','AbortController|AbortSignal|abort controller|abort signal|请求取消|取消信号','frontend',
 'AbortController创建可传递的AbortSignal，调用abort通知支持该协议的异步操作停止等待或执行取消。',
 'fetch可接收signal，取消通常使Promise以AbortError拒绝；取消是协作式的，服务端可能已完成写入。界面还应以请求版本检查结果，阻止已完成的旧响应覆盖新状态。',
 '搜索联想怎样避免旧请求覆盖新结果？','先取消上一次请求，再记录当前查询的递增版本；写入状态时比较版本，组件卸载时取消任务，并把预期取消与真实网络错误分开处理。',
 '一个已abort的signal可以复用来重试吗？','不能恢复其状态，新任务需要新控制器；若将同一signal传给多个操作，abort会通知整组操作，适合按页面或交互统一管理生命周期。'),
('wsgi-protocol','Python同步网关协议 (WSGI)','WSGI|web server gateway interface|wsgi application|start_response|同步网关协议|WSGI协议','backend',
 'WSGI约定Python Web服务器通过application(environ, start_response)调用应用，应用返回响应字节块的可迭代对象。',
 '它描述服务器与应用的同步接口，不决定服务器的线程或进程数。流式响应可以逐块产出，但长连接通常占用工作槽；WebSocket双向事件流需要其他协议支持。',
 '使用WSGI意味着整个服务只能处理一个请求吗？','不是，服务器可配置多进程或线程，每个工作单元执行同步调用；并发上限和阻塞行为要结合工作模型、连接池与下游服务评估。',
 'WSGI应用返回字符串而不是字节块有什么问题？','协议要求响应体迭代产生bytes；编码应在应用边界明确完成，同时通过Content-Type声明字符集，响应头由start_response提交。'),
('asgi-protocol','Python异步网关协议 (ASGI)','ASGI|asynchronous server gateway interface|asgi application|异步网关协议|ASGI协议|scope receive send','backend',
 'ASGI应用通过异步可调用对象接收scope、receive、send，以消息形式处理HTTP、WebSocket及生命周期事件。',
 'scope描述连接上下文，receive和send交换协议事件。并发收益依赖非阻塞IO；异步函数直接调用阻塞数据库或CPU循环仍会堵住事件循环，需要合适的驱动或执行池。',
 'ASGI支持异步，为什么接口仍被一个慢请求拖住？','检查async函数中是否直接调用同步IO或长CPU计算；用异步驱动处理IO、将必要的阻塞操作交给受控执行池，并监控事件循环延迟。',
 'WSGI应用能直接当ASGI应用调用吗？','两者参数与生命周期不同，需要协议适配器；适配通常把同步工作交给线程，不能自动赋予同步应用WebSocket或真正的异步IO能力。'),
('topological-sort','拓扑排序 (Topological Sort)','topological sort|topological ordering|拓扑排序|拓扑序|Kahn algorithm|Kahn算法','system',
 '拓扑排序为有向无环图产生线性顺序，使每条先决条件指向后继的边都满足先决条件在前；多个合法顺序可能同时存在。',
 'Kahn算法维护入度为零的队列，逐步删除出边，复杂度O(V+E)。若处理节点数少于总数则存在环；代码图若采用文件指向依赖的边，执行依赖优先排序需反向解释。',
 '架构图中的依赖箭头能直接拿来做构建顺序吗？','先确定边的语义。A指向B若表示A依赖B，应让B先执行；可反转边再拓扑排序，循环依赖则应显式报告或先凝聚强连通分量。',
 '拓扑序为何每次生成不一样？','多个零入度节点可任选；用稳定路径或优先队列打破平局即可得到可复现结果，稳定顺序并不意味着依赖关系本身唯一。'),
('strongly-connected-component','强连通分量 (Strongly Connected Component)','strongly connected component|SCC|强连通分量|Tarjan algorithm|Kosaraju algorithm|强连通子图','system',
 '有向图中任意两个节点都能互相到达的极大节点集合称为强连通分量，可用于定位循环依赖。',
 'Tarjan以DFS序号、low-link及栈在线识别分量，Kosaraju使用两次遍历。将每个分量压成一个节点后得到有向无环的凝聚图，便于分层布局与依赖分析。',
 '发现A依赖B、B依赖A时应删除一条边来画图吗？','应保留真实依赖，把循环部分标成同一强连通分量，再对凝聚图分层；随意删边会掩盖耦合，架构重构与布局处理应分开。',
 '强连通与弱连通有什么区别？','强连通要求遵循方向能双向到达；弱连通忽略方向后连通即可。弱连通可划分独立子图，但不能直接识别循环依赖。'),
('singleflight','同键请求合并 (Singleflight)','singleflight|single flight|request coalescing|请求合并|同键请求合并|in flight deduplication','system',
 'Singleflight把同一时刻针对相同键的重复计算合并，让一个执行者计算，其他调用者等待并共享本次结果。',
 '它去重进行中的工作而非长期缓存。键必须包含项目、语言、版本等影响结果的维度；完成或失败后释放进行中记录，避免错误永久卡住后续请求。',
 '缓存已经存在，为何还需要同键请求合并？','冷启动或过期瞬间多个请求同时未命中，会一起打向数据库或模型；缓存负责复用已完成结果，singleflight负责合并这段并发空窗。',
 '等待者取消时能否直接取消共享计算？','通常只取消该等待者；其他调用者仍需要结果。应区分共享任务生命周期与各自等待期限，并确保失败能通知全部等待者。'),
('eventual-consistency','最终一致性 (Eventual Consistency)','eventual consistency|最终一致性|eventually consistent|异步副本收敛|一致性收敛|副本同步','system',
 '在没有持续新写入且更新能够传播的条件下，系统副本最终收敛到一致状态；它本身不承诺收敛时限或读到最新值。',
 '异步复制提升可用性与延迟表现，但会出现旧读、乱序和冲突。版本号、幂等消费、冲突解决以及读己之写等额外保证，需要分别设计和验证。',
 '最终一致性是否等于数据库事务中的一致性？','不是。ACID一致性关注事务维持数据约束，副本一致性关注多节点读写可见性；单节点事务正确并不保证远端副本立即读到更新。',
 '订单已支付但页面仍显示未支付，如何排查？','沿支付提交、事件发布、消费、读模型及缓存检查版本和延迟；消费应幂等并可重放，界面可显示处理中，不能靠盲目重复支付弥补旧读。'),
('learning-to-rank','学习排序 (Learning to Rank)','learning to rank|LTR|学习排序|ranking model|排序模型|排序学习','ml',
 '学习排序使用查询、候选与相关性反馈训练评分或排序函数，用于搜索、推荐和RAG精排。',
 'Pointwise预测单项标签，pairwise优化相对偏好，listwise面向整组列表目标。训练与评估按查询组织，注意曝光偏差、负样本构成与候选召回上限，离线指标不能代替在线收益。',
 '分类AUC提高，搜索NDCG为什么可能下降？','全局分类更好不代表同一查询的头部排序更好；检查查询内排序、位置权重、标签分级及数据切分，使用与产品目标一致的分组指标。',
 '精排模型能救回召回阶段漏掉的文档吗？','只能在候选中重排，缺失文档需要改召回；应分别评估候选Recall@K和固定候选集上的精排NDCG，避免把两阶段混成一个指标。'),
('pairwise-ranking','成对排序 (Pairwise Ranking)','pairwise ranking|pairwise loss|成对排序|成对损失|RankNet|ranking pair','ml',
 '成对排序以同一查询下两个候选的偏好为训练信号，推动较优候选的得分高于较差候选。',
 '常用logistic或hinge损失作用于分数差，分数整体平移不改变成对偏好。全量候选对数量为平方级，采样策略、困难负例与标签噪声会显著影响训练。',
 '为什么排序训练配对通常限制在同一查询内？','不同查询的标签和难度不一定可比较；同查询配对更直接反映用户决策，跨查询配对需额外证明可比性，不能随意组合。',
 '只选最难负例一定最好吗？','可能集中放大误标和假负例，导致训练不稳定；应混合难度、过滤冲突标签并检查梯度与分组指标，评估相对随机采样的收益。'),
('listwise-ranking','列表级排序 (Listwise Ranking)','listwise ranking|listwise loss|列表级排序|列表损失|ListNet|ListMLE','ml',
 '列表级排序以同一查询的候选列表作为训练单位，通过列表概率分布或排列似然学习整体排序。',
 'ListNet可匹配目标与预测的列表分布，ListMLE优化标注排列的似然。候选截断、同分标签处理和查询间长度差异会改变目标权重；列表损失不天然等于直接优化NDCG。',
 'listwise比pairwise一定效果更好吗？','取决于目标、标签质量和候选构成；列表目标能表达组内竞争，但训练成本与截断偏差更明显，应在相同候选和切分条件下比较。',
 '训练每个查询只保留十个候选，线上排一千个有什么风险？','竞争分布和难负例覆盖不同，可能导致泛化变差；应让采样覆盖线上候选分布，并按候选规模分桶验证头部指标。'),
('gradient-clipping','梯度裁剪 (Gradient Clipping)','gradient clipping|clip grad norm|clip_grad_norm_|梯度裁剪|全局范数裁剪|gradient norm clipping','ml',
 '梯度裁剪限制梯度值或范数，减轻异常大梯度造成的参数更新突变；全局范数裁剪按共同系数缩放全部梯度。',
 '阈值为c、梯度范数为g时乘min(1,c/g)，保留当前梯度方向。混合精度应先反缩放再裁剪，梯度累积通常在最终累积后裁剪，仍需查明频繁爆梯度的根因。',
 '梯度裁剪等同于降低学习率吗？','不是，降低学习率缩小所有更新，裁剪主要限制超过阈值的梯度；自适应优化器还有动量与预条件，最终参数步长不只由当前梯度范数决定。',
 '混合精度下直接裁剪放大后的梯度有什么问题？','裁剪阈值会被损失缩放系数改变，得到错误有效更新；先unscale，再检测非有限值和裁剪，记录裁剪比例以判断训练是否持续异常。'),
('reservoir-sampling','蓄水池抽样 (Reservoir Sampling)','reservoir sampling|蓄水池抽样|水塘抽样|reservoir sample|流式均匀抽样|Algorithm R','ml',
 '蓄水池抽样在不知道数据流总长度时，以O(k)内存保留k个样本，使每个已到达元素具有相同入样概率。',
 '先保留前k项，第i项到达时均匀采样1到i，结果不超过k则替换对应槽。处理n项后每项入选概率为k/n；加权流或时间衰减需要不同算法。',
 '为什么每次都以固定概率替换样本不均匀？','新项进入概率与旧项存活过程不匹配；Algorithm R让第i项以k/i进入，结合后续存活概率可推得所有元素最终均为k/n。',
 '两个分片各抽k条，再直接合并抽k条能保持均匀吗？','分片大小不同时通常不能，较小分片会过度代表；需携带分片计数进行正确加权合并，或使用可合并的随机优先级抽样。'),
]

CATEGORY = {'web':'前端工程','frontend':'前端工程','backend':'后端与分布式','system':'分布式系统与微服务','llm':'Agent应用开发','ai':'AI算法与检索','ml':'业务算法与训练基础'}
ENTRY_REFERENCES = {
    'threading-http-server': 'https://github.com/python/cpython/blob/main/Lib/http/server.py',
    'asgi-protocol': 'https://github.com/django/asgiref/blob/main/specs/asgi.rst',
    'wsgi-protocol': 'https://github.com/django/asgiref/blob/main/specs/asgi.rst',
}
RELATED = {
    'threading-http-server': ['http-protocol', 'threading-concurrency', 'sse-eventsource'],
    'abort-controller': ['promise', 'async-await', 'race-condition'],
    'wsgi-protocol': ['asgi-protocol', 'http-protocol', 'threading-http-server'],
    'asgi-protocol': ['wsgi-protocol', 'async-await', 'backpressure'],
    'topological-sort': ['strongly-connected-component', 'pagerank-algorithm'],
    'strongly-connected-component': ['topological-sort', 'pagerank-algorithm'],
    'singleflight': ['local-cache', 'mutex-semaphore', 'idempotency'],
    'eventual-consistency': ['acid-transactions', 'idempotency'],
    'learning-to-rank': ['pairwise-ranking', 'listwise-ranking', 'ndcg-metric'],
    'pairwise-ranking': ['learning-to-rank', 'listwise-ranking'],
    'listwise-ranking': ['learning-to-rank', 'pairwise-ranking'],
    'gradient-clipping': ['gradient-descent', 'gradient-accumulation'],
    'reservoir-sampling': ['negative-sampling', 'data-leakage'],
}
EXTRA_ENTRIES = []
for identifier, name, aliases, domain, definition, detail, q1, a1, q2, a2 in ROWS:
    reference = ENTRY_REFERENCES.get(identifier, SOURCES[domain])
    EXTRA_ENTRIES.append({
        'id': identifier, 'name': name, 'aliases': aliases.split('|'),
        'category': CATEGORY[domain], 'definition': definition, 'detailed_explanation': detail,
        'related_concepts': RELATED.get(identifier, {
            'web':['js-event-loop','dom-tree'], 'frontend':['dom-tree','css-grid'],
            'backend':['transaction-isolation','threading-concurrency'],
            'system':['backpressure','idempotency'], 'llm':['rag-pipeline','tokenizer'],
            'ai':['embedding-vector','bm25-ranking'], 'ml':['gradient-descent','data-leakage']}[domain]),
        'references': [reference],
        'interview_questions': [
            {'question': q1, 'answer': a1, 'kind': 'curated', 'reference': reference},
            {'question': q2, 'answer': a2, 'kind': 'curated', 'reference': reference},
        ],
    })
